### ISSUE TITLE
Need web.config file

### ISSUE THREAD

**Issue by aarongustafson** [petrvondrasek/cms#1]
The server will be IIS, not Apache.

**Comment by aarongustafson** [comment]
@petrvondrasek We need this ASAP or we will need to reject the entry.

**Comment by petrvondrasek** [comment]
Fixed, tested on W10, IIS, PHP 6.3, web.config added and is needed only for enabling compression.

I have added some more info about the project to readme.txt - could be used in description.

Thanks.
